### ISSUE TITLE
Error creating .vtt subtitle file

### ISSUE THREAD

**Issue by themebon** [mkly/youtube-closed-captions#8]
When i run this 

`from ytcc.download import Download

video_id = 'w7ejDZ8SWv8'
download = Download()
# Language is optional and default to "en"
# YouTube uses "en","fr" not "en-US", "fr-FR"
captions = download.get_captions(video_id, 'en')

print(captions)`

This will throw error 

`Traceback (most recent call last):
  File "C:\Users\Raju\Desktop\YoutubeDL\main.py", line 7, in <module>
    captions = download.get_captions(video_id, 'en')
  File "C:\Users\Raju\Desktop\YoutubeDL\ytcc\download.py", line 37, in get_captions
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'subtitle_w7ejDZ8SWv8.en.vtt'`

Can you please fix this

**Comment by mkly** [comment]
Fixed in master: added writesubtitles/subtitlesformat options and proper DownloadException handling when caption files do not exist.
